<?php
//
// ETS2MP Homepage language file.
// File: thai.php
// Language name: Thai
// Translated name: ภาษาไทย
//

$_lang["download"] = "ดาวน์โหลด";
$_lang["home"] = "หน้าหลัก";
$_lang["status"] = "สถานะเซิร์ฟเวอร์";
$_lang["username"] = "ชื่อผู้ใช้";
$_lang["password"] = "รหัสผ่าน";
$_lang["login"] = "เข้าสู่ระบบ";
$_lang["register"] = "ลงทะเบียน";
$_lang["download.latest.version"] = "ดาวน์โหลดเวอร์ชั่นล่าสุด";
$_lang["current.release"] = "เวอร์ชั่นปัจจุบัน:";
$_lang["language"] = "ภาษา";
$_lang["join"] = "เข้าร่วม";
$_lang["mainpage.join"] = "เข้าร่วมกับผู้ขับรถบรรทุกกว่าพันคนออนไลน์!";
$_lang["ts3.advertisement"] = "สื่อสารผ่านเสียงกับผู้ขับรถอื่นๆ คลิกที่นีเพื่อเข้าร่วมกับเราในเซิร์ฟเวอร์ TS3";
$_lang["facebook.advertisement"] = "ข่าวสารล่าสุดจาก Facebook";
$_lang["registration.blocked"] = "การลงทะเบียนถูกปิดอยู่ เรากำลังปรับปรุงคุณสมบัติเกมจึงจำเป็นต้อนปิดการลงทะเบียน เราจะเปิดให้ลงทะเบียนเมื่อทุกอย่างพร้อมสำหรับเวอร์ชั่นใหม่เรียบร้อยแล้ว";
$_lang["invalid.username.password"] = "อีเมลล์หรือรหัสผ่านไม่ถูกต้อง";
$_lang["already.logged"] = "คุณได้เข้าระบบอยู่แล้ว";
$_lang["welcome"] = "ยินดีต้อนรับ";
$_lang["logout"] = "ออกจากระบบ";
$_lang["bans"] = "รายชื่อการโดนแบน";
$_lang["version"] = "เวอร์ชั่น";
$_lang["update.time"] = "เวลาที่อัพเดท";
$_lang["req.game.version"] = "เวอร์ชั่นเกมที่ต้องการ";
$_lang["requires"] = "ต้องการ";
$_lang["or.newer"] = "หรือใหม่กว่า";
$_lang["game.client"] = "ตัว Client";
$_lang["download.no.permissions"] = "ทำการเข้าสู่ระบบเพื่อทำการดาวน์โหลด";
$_lang["why.create.account"] = "ทำไมต้องสร้างชื่อผู้ใช้?<br />ชื่อหนึ่งจะถูกใช้ในการเข้าสู่ทุกระบบ (กระทู้ เกม ระบบเศรฐกิจ และอื่นๆ)  เราวางแผนที่จะใช้ในการสร้างระบบเศรฐกิจ และข้อมูลสถิติของคนขับ ในอนาคตนี้ และคุณจะสามารถแก้ไขข้อมูลเหล่านี้ได้";
$_lang["website.title"] = "ETS2MP - โลกเสมือนจริงสำหรับรถบรรทุก - ม๊อดผู้เล่นหลายคนสำหรับเกม Euro Truck Simulator 2 โดย SCS Software";
$_lang["cookies.warning"] = "เว็บไซต์นี้ใช้ <a href=\"http://en.wikipedia.org/wiki/HTTP_cookie\">cookies</a>. คุณตกลงที่จะใช้ cookies เมื่อคุณทำการเข้าสู่เว็บไซต์นี้ต่อไป";
$_lang["forum"] = "บอร์ดสนทนา";
$_lang["cannot.create.account.when.logged"] = "คุณไม่สามารถสร้างผู้ใช้ใหม่ได้ หากคุณเข้าสู่ระบบอยู่";
$_lang["successfully.registered"] = "คุณได้ลงทะเบียนสำเร็จเรียบร้อยแล้ว โปรดตรวจสอบอีเมลล์ของคุณเพื่อเปิดใช้งานชื่อผู้ใช้ อีเมลล์: <b>{0}</b>";
$_lang["error.unknown"] = "เกิดข้อผิดพลาดไม่ทราบประเภท";
$_lang["credentials.taken"] = ""ชื่อ อีเมลล์ หรือชื่อ Steam ได้ถูกใช้แล้ว";
$_lang["error.no.steam.data"] = "ในการสร้างชื่อผู้ใช้ ETS2MP คุณต้องมีเกม Euro Truck Simulator 2 อยู่ในคลัง Steam ของคุณ  หากคุณมีอยู่ในคลังแล้ว ลองตรวจสอบว่าโปรไฟล์ของคุณเปิดให้สาธารณะมองเห็นได้ ถ้าโปรไฟล์ของคุณเป็นแบบส่วนตัวอยู่ ให้เปลี่ยนเป็นแบบสาธารณะแล้วกดตกลง";
$_lang["register.steam.info"] = "ในการสร้างชื่อผู้ใช้ คุณต้องเข้าสู่ระบบ Steam กดปุ่มด้านล่างเพื่อไปสู่เว็บไซต์ในการยืนยันการเข้าสู่ระบบ";
$_lang["rules.info"] = "คุณยอมรับกฎระเบียบของกลุ่มเรา เมื่อคุณกดยืนยันการลงทะเบียน อ่านกฎระเบียบดังกล่าวโดยการคลิกที่นี่";
$_lang["mail"] = "อีเมลล์";
$_lang["repeat.mail"] = "อีเมลล์อีกครั้ง";
$_lang["new.password"] = "รหัสผ่านใหม่";
$_lang["repeat.new.password"] = "รหัสผ่านใหม่อีกครั้ง";
$_lang["new.password.summary"] = "ปล่อยว่างหากไม่ต้องการเปลี่ยนรหัสผ่าน";
$_lang["old.password"] = "รหัสผ่านปัจจุบัน";
$_lang["repeat.old.password"] = "รหัสผ่านปัจจุบันอีกครั้ง";
$_lang["save.account.data"] = "บันทึกข้อมูลผู้ใช้";
$_lang["edit.account"] = "แก้ไขบัญชึผู้ใช้";
$_lang["forgot.password"] = "ลืมรหัสผ่าน? คลิก <a href=\"index.php?page=resetPassword\">ที่นี่</a>.";
$_lang["forgot.password.summary"] = "หากคุณลิมรหัสผ่าน ให้พิมพ์อีเมลล์ด้านล่างนี้ แล้วกดปุ่ม \"ลิมรหัสผ่าน\"";
$_lang["reminder.button"] = "ลืมรหัสผ่าน";
$_lang["reset.password"] = "ตั้งรหัสผ่านใหม่";
$_lang["password.reminder.mail.title"] = "การขอตั้งรหัสผ่านใหม่";
$_lang["password.reminder.content"] = "สวัสดีครับ\n\nมีใครบางคนจาก IP {0} ได้ทำการขอตั้งรหัสผ่านของบัญชึผู้ใช้ ETS2MP ของคุณใหม่\n\nหากต้องการตั้งรหัสผ่านใหม่ให้คลิกที่ลิงค์นี้: {1}.\nหากคุณไม่ได้เป็นผู้ขอ ไม่ต้องทำอะไรทั้งสิ้น\n\nขอบคุณครับ\nทีมงาน ETS2MP";
$_lang["new.password.mail.title"] = "รหัสผ่านใหม่ของคุณ";
$_lang["new.password.mail.content"] = "สวัสดีครับ\n\nนี่คือรหัสผ่านใหม่ของคุณ: {0}\n\nอย่าลิมเปลี่ยนรหัสผ่านของคุณทันทีหลังเข้าสู่ระบบ\n\nขอบคุณครับ\nทีมงาน ETS2MP";
$_lang["account.activated"] = "คุณได้ทำการยืนยันบัญชีผู้ใช้เรียบร้อยแล้ว";
$_lang["unable.to.activate"] = "ไม่สามารถยืนยันบัญชีได้ รหัสยืนยันไม่ถูกต้อง หรือบัญชีผู้ใช้ได้รับการยืนยันเรียบร้อยแล้ว";
$_lang["not.activated"] = "บัญชึผู้ใช้ของคุณยังไม่ได้ทำการยืนยัน หากคุณไม่ได้รับข้อความยืนยัน ให้คลิก <a href=\"index.php?action=resendActivation\">ที่นี่</a> เพื่อส่งข้อความยืนยันใหม่";
$_lang["force.password.change"] = "กรุณาเปลี่ยนรหัสผ่านของคุณทันที คลิก <a href=\"index.php?page=editAccount\">ที่นี่</a> เพื่อเปลี่ยนรหัสผ่าน";
$_lang["forgot.password.link.sent"] = "ตรวจสอบอีเมลล์ของคุณ เราได้ทำการส่งลิงค์ในการตั้งรหัสผ่านใหม่ไปแล้ว";
$_lang["forgot.password.sent"] = "ตรวจสอบอีเมลล์ของคุณ เราได้ทำการส่งรหัสผ่านใหม่ให้แล้ว";
$_lang["forgot.password.invalid.key"] = "รหัสยืนยันไม่ถูกต้อง";
$_lang["activation.key.resent"] = "รหัสยืนยันได้ถูกส่งไปใหม่ที่อีเมลล์ของคุณแล้ว";
$_lang["activation.mail.title"] = "ยืนยันบัญชึผู้ใช้ ETS2MP";
$_lang["activation.mail.content"] = "สวัสดีครับ\n\nนี่คือรหัสยืนยันของคุณ: {0}\n\nขอบคุณครับ\nทีมงาน ETS2MP";
$_lang["no.login"] = "คุณต้องทำการเข้าสู่ระบบ ในการเข้าเว็บไซต์นี้";
$_lang["settings.saved.with.mail"] = "บัญชีถูกบันทึกเรียบร้อย ตรวจสอบอีเมลล์ของคุณเพื่อทำการยืนยันอีกครั้ง";
$_lang["new.email.in.use"] = "อีเมลล์นี้ถูกใช้งานแล้ว";
$_lang["email.does.not.match"] = "อีเมลล์ที่ใส่มาไม่ตรงกัน";
$_lang["invalid.email.format"] = "อีเมลล์ทึ่ใส่มาไม่ถูกต้อง";
$_lang["new.password.does.not.match"] = "รหัสผ่านใหม่ที่ใส่มาไม่ตรงกัน";
$_lang["too.short.password"] = "รหัสผ่านใหม่สั้นเกินไป ต้องมีความยาวอย่างน้อย 5 ตัวอักษร";
$_lang["old.password.does.not.match"] = "รหัสผ่านปัจจุบันไม่ถูกต้อง";
$_lang["settings.saved"] = "บัญชีถูกบันทึกเรียบร้อย";
$_lang["invalid.old.password"] = "รหัสผ่านปัจจุบันไม่ถูกต้อง ไม่สามารถบันทึกข้อบัญชีได้";
$_lang["no.password.change.forced"] = "ต้องทำการออกจากระบบ เพื่อขอตั้งรหัสผ่านใหม่";
$_lang["password.reminder.edit.account"] = "ลืมรหัสผ่าน? คลิก <a href=\"index.php?page=resetPassword\">ที่นี่</a>.";
$_lang["contact"] = "ติดต่อทีมงาน";
$_lang["your.mail"] = "อีเมลล์ของคุณ";
$_lang["content"] = "เนื้อหา";
$_lang["send"] = "ส่ง";
$_lang["contact.message.sent"] = "ขอบคุณที่ติดต่อเรา กรุณารอการตอบกลับ";
$_lang["topic"] = "หัวข้อ";
$_lang["contact.message.too.short"] = "ข้อความสั้นเกินไป ต้องมีความยาวอย่างน้อย 10 ตัวอักษร";
$_lang["contact.topic.too.short"] = "หัวข้อสั้นเกินไป ต้องมีความยาวอย่างน้อย 10 ตัวอักษร";
$_lang["invalid.mail.forgot.password"] = "เราไม่สามารถค้นหาชื่อบัญชีผู้ใช้ที่ตรงกับอีเมลล์นี้ได้";
$_lang["steamid.in.use"] = "เราตรวจพบบัญชีผู้ใช้ของ ETS2MP ที่ได้เข้าสู่ระบบของบัญชี Steam นี้แล้ว. หากคุณมีปัญหากับการลงทะเบียน กรุณา <a href=\"http://ets2mp.com/support/\">สร้าง ticket เพื่อแจ้งปัญหา</a>.";
$_lang["mail.does.not.match"] = "อีเมลล์ที่ใส่มาไม่ถูกตรวจพบ";
$_lang["support"] = "แจ้งปัญหา";
$_lang["profile"] = "โปรไฟล์";
$_lang["group"] = "กลุ่ม";
$_lang["banned"] = "ถูกระงับการใช้งาน";
$_lang["state"] = "สถานะ";
$_lang["account.is.activated"] = "บัญชีผู้ใช้ได้รับการยืนยันแล้ว";
$_lang["account.isnt.activated"] = "บัญชีผู้ใช้ยังไม่ได้รับการยืนยัน";
$_lang["penalty.history"] = "ประวัติการลงโทษ";
$_lang["no.punishments"] = "ไม่มีประวัติการลงโทษให้แสดง";
$_lang["date"] = "วันที่";
$_lang["reason"] = "เหตุผล";
$_lang["type"] = "ประเถท";
$_lang["penalty.limit"] = "เฉพาะเจ้าของบัญชีผู้ใช้เท่านั้นจะสามารถแสดงประวัติการลงโทษทั้งหมดได้";
$_lang["error.cannot.fetch.steam.api"] = "ไม่สามารถนำข้อมูลโปรไฟล์ของคุณจาก Steam ได้ ลองใหม่อีกครั้งในภายหลัง";
